### ISSUE TITLE
Softwareupdate error in the new image [1]

### ISSUE THREAD

**Issue by JFSolution** [mrbeam/BeamOS#44]
it looks like there is a error in the software_update_information.py
```
2021-04-20 11:11:03,276 - octoprint.plugins.findmymrbeam - INFO - FindMyMrBeam registration: OK - ip4_status: 200, public_ip: 212.114.227.216, ip6_status: 200, public_ip6: 2001:a61:58a:9001:ba27:ebff:fe88:95ff, hostname: MrBeam-5595, local_ips: 192.168.100.193, netconnectd_state: {'ap': False, 'wifi': True, 'wired': False}, internal_modes: []
2021-04-20 11:11:03,280 - octoprint.plugins.softwareupdate - ERROR - Error while retrieving update information from plugin mrbeam
Traceback (most recent call last):
 File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 111, in _get_configured_checks
  hook_checks = hook()
 File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/__init__.py", line 2544, in get_update_information
  return get_update_information(self)
 File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/util/log.py", line 83, in wrapped
  ret = f(*a, **kw)
 File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/software_update_information.py", line 57, in get_update_information
  _set_info_netconnectd_daemon(plugin, tier, beamos_date),
 File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/software_update_information.py", line 193, in _set_info_netconnectd_daemon
  version = get_version_of_pip_module(package_name, pip_command)
NameError: global name 'package_name' is not defined
2021-04-20 11:11:03,291 - octoprint.plugins.softwareupdate - WARNING - Unknown update check type for target netconnectd: <n/a>
```

**Comment by amrsoll** [comment]
This particular error should have been fixed now :) Thanks
